name: portfolio
on: push
jobs:
  deploy-prod:
    name: 'Deploy PROD Server'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_NAME: ${{ secrets.REGISTRY_URL }}/${{ secrets.PROJECT_ID }}/${{ secrets.APP_NAME }}:latest
      API_URL: ${{ secrets.API_FRONTEND_URL }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
      - name: 'Authorize Docker push'
        run: 'gcloud auth configure-docker --quiet'
      - name: 'Build Docker image'
        run: 'docker build . -t $IMAGE_NAME'
      - name: 'Test Docker image'
        run: 'docker run -d -p 80:80 $IMAGE_NAME'
      - name: 'Push Docker image'
        run: 'docker push $IMAGE_NAME'
      - name: 'Deploy Docker image'
        run: |
          gcloud run deploy ${{ secrets.APP_NAME }} \
          --image $IMAGE_NAME \
          --region ${{ secrets.REGION}} \
          --platform managed \
          --min-instances ${{ secrets.GCP_MIN_INSTANCES }} \
          --max-instances ${{ secrets.GCP_MAX_INSTANCES }} \
          --concurrency ${{ secrets.GCP_CONCURRENCY }} \
          --port 80 \
          --cpu ${{ secrets.GCP_CPU }} \
          --memory ${{ secrets.GCP_MEMORY }} \
          --allow-unauthenticated