name: portfolio
on: push
jobs:
  deploy:
    name: 'Deploy portfolio'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      PROFILE_ACTIVE: prod
      GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
      REPOSITRORY: ${{ secrets.REGION }}-docker.pkg.dev
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
        - name: 'Checkout'
          uses: actions/checkout@v3
        - name: 'Auth'
          uses: google-github-actions/auth@v0
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        - name: 'Set up Cloud SDK'
          uses: google-github-actions/setup-gcloud@v0
        - name: 'Docker auth configuration'
          run: gcloud auth configure-docker
        - name: Generate Image Tag
          run: |
            echo "IMAGE_URL=${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.APP_NAME }}/${{ secrets.APP_NAME }}:${GITHUB_SHA::8}" >> $GITHUB_ENV
        - name: 'Build image'
          run: docker build --build-arg api_url="$API_URL" . --tag $IMAGE_URL
        - name: 'Docker push image'
          run: |-
            gcloud auth configure-docker $REPOSITRORY
            docker push "$IMAGE_URL"
        - name: 'Deploy Docker image'
          run: |
            gcloud run deploy ${{ secrets.APP_NAME }} \
              --image $IMAGE_URL \
              --region ${{ secrets.REGION}} \
              --platform managed \
              --min-instances ${{ secrets.GCP_MIN_INSTANCES }} \
              --max-instances ${{ secrets.GCP_MAX_INSTANCES }} \
              --concurrency ${{ secrets.GCP_CONCURRENCY }} \
              --port 80 \
              --cpu ${{ secrets.GCP_CPU }} \
              --memory ${{ secrets.GCP_MEMORY }} \
              --allow-unauthenticated